#include <common.h>
#include <npcdata.h>
#include <spm_system.h>
#include <stdio.h>
#include <stdlib.h>

/* Data generated by SPM-CRACKPIPE-1337 by Yme */

ItemData itemDataTable[] = {
    {"Fire Burst", 65, 10},
    {"Ice Storm", 66, 20},
    {"Thunder Rage", 67, 40},
    {"Shooting Star", 68, 80},
    {"POW Block", 69, 40},
    {"Shell Shock", 70, 10},
    {"Gold Bar", 71, 90},
    {"Gold Bar x3", 72, 275},
    {"Block Block", 73, 25},
    {"Courage Shell", 74, 5},
    {"Mighty Tonic", 75, 35},
    {"Volt Shroom", 76, 15},
    {"Ghost Shroom", 77, 44},
    {"Sleepy Sheep", 78, 5},
    {"Stop Watch", 79, 25},
    {"Shroom Shake", 80, 15},
    {"Super Shroom Shake", 81, 40},
    {"Ultra Shroom Shake", 82, 150},
    {"Dried Shroom", 83, 1},
    {"Life Shroom", 84, 50},
    {"Long-Last Shake", 85, 15},
    {"Mystery Box", 86, 5},
    {"Catch Card", 87, 10},
    {"Catch Card SP", 88, 50},
    {"HP Plus", 89, 400},
    {"Power Plus", 90, 400},
    {"Blue Apple", 91, 15},
    {"Orange Apple", 92, 15},
    {"Red Apple", 93, 15},
    {"Pink Apple", 94, 15},
    {"Black Apple", 95, 1},
    {"Star Medal", 96, 25},
    {"Gold Medal", 97, 250},
    {"Poison Shroom", 98, 2},
    {"Slimy Shroom", 99, 20},
    {"Peachy Peach", 100, 13},
    {"Keel Mango", 101, 10},
    {"Primordial Fruit", 102, 25},
    {"Golden Leaf", 103, 45},
    {"Turtley Leaf", 104, 5},
    {"Cake Mix", 105, 13},
    {"Whacka Bump", 106, 150},
    {"Horsetail", 107, 9},
    {"Fresh Pasta Bunch", 108, 15},
    {"Hot Sauce", 109, 10},
    {"Inky Sauce", 110, 15},
    {"Dayzee Tear", 111, 25},
    {"Sap Soup", 112, 8},
    {"Bone-In Cut", 113, 30},
    {"Fresh Veggie", 114, 10},
    {"Smelly Herb", 115, 8},
    {"Honey Jar", 116, 10},
    {"Power Steak", 117, 18},
    {"Big Egg", 118, 13},
    {"Mild Cocoa Bean", 119, 10},
    {"Sweet Choco-bar", 120, 5},
    {"Shroom Choco-bar", 121, 25},
    {"Golden Choco-bar", 122, 50},
    {"Gradual Syrup", 123, 50},
    {"Dayzee Syrup", 124, 35},
    {"Slimy Extract", 125, 30},
    {"Fried Shroom Plate", 126, 35},
    {"Roast Shroom Dish", 127, 96},
    {"Shroom Steak", 128, 180},
    {"Honey Shroom", 129, 58},
    {"Honey Super", 130, 118},
    {"Shroom Broth", 131, 55},
    {"Mushroom Crepe", 132, 65},
    {"Shroom Cake", 133, 125},
    {"Chocolate Cake", 134, 55},
    {"Heartful Cake", 135, 75},
    {"Mousse", 136, 60},
    {"Peach Tart", 137, 50},
    {"Horsetail Tart", 138, 60},
    {"Sweet Cookie Snack", 139, 30},
    {"Koopa Dumpling", 140, 40},
    {"Sap Muffin", 141, 55},
    {"Town Special", 142, 27},
    {"Mango Pudding", 143, 55},
    {"Love Pudding", 144, 75},
    {"Couple's Cake", 145, 150},
    {"Fruit Parfait", 146, 70},
    {"Snow Cone", 147, 43},
    {"Snow Bunny", 148, 5},
    {"Berry Snow Bunny", 149, 5},
    {"Honey Candy", 150, 24},
    {"Electro Pop", 151, 82},
    {"Herb Tea", 152, 18},
    {"Koopa Tea", 153, 9},
    {"Spaghetti Plate", 154, 35},
    {"Spicy Pasta Dish", 155, 60},
    {"Ink Pasta Dish", 156, 63},
    {"Koopasta Dish", 157, 45},
    {"Love Noodle Dish", 158, 80},
    {"Fried Egg", 159, 30},
    {"Egg Bomb", 160, 50},
    {"Dyllis Dynamite", 161, 66},
    {"Roast Meat", 162, 50},
    {"Meteor Meal", 163, 205},
    {"Omelette Plate", 164, 50},
    {"Spicy Soup", 165, 23},
    {"Hot Dog", 166, 60},
    {"Healthy Salad", 167, 28},
    {"Dyllis Dinner", 168, 100},
    {"Dyllis Special", 169, 160},
    {"Dyllis Deluxe", 170, 225},
    {"Space Food", 171, 60},
    {"Emergency Ration", 172, 40},
    {"Dangerous Delight", 173, 3},
    {"Trial Stew", 174, 2},
    {"Mistake", 175, 1},
    {"Mistake", 176, 1},
    {"Warm Cocoa", 177, 25},
    {"Odd Dinner", 178, 33},
    {"Inky Soup", 179, 20},
    {"Gingerbread House", 180, 130},
    {"Volcano Shroom", 181, 60},
    {"Koopa Pilaf", 182, 45},
    {"Spicy Dinner", 183, 40},
    {"Shroom Pudding", 184, 65},
    {"Heavy Meal", 185, 10},
    {"Primordial Dinner", 186, 60},
    {"Gorgeous Steak", 187, 75},
    {"Golden Meal", 188, 50},
    {"Luxurious Set", 189, 50},
    {"Roast Whacka Bump", 190, 200},
    {"Dyllis Breakfast", 191, 60},
    {"Dyllis Lunch", 192, 75},
    {"Sky Juice", 193, 20},
    {"Stamina Juice", 194, 50},
    {"Choco Pasta Dish", 195, 60},
    {"Shroom Delicacy", 196, 55},
    {"Roast Horsetail", 197, 25},
    {"Sap Syrup", 198, 20},
    {"Hamburger", 199, 40},
    {"Peach Juice", 200, 28},
    {"Standard Chocolate", 201, 4},
    {"Fruity Cake", 202, 90},
    {"Fruity Hamburger", 203, 65},
    {"Fruity Punch", 204, 55},
    {"Fruity Shroom", 205, 60},
    {"Block Meal", 206, 53},
    {"Veggie Set", 207, 60},
    {"Weird Extract", 208, 55},
    {"Awesome Snack", 209, 55},
    {"Mango Juice", 210, 23},
    {"Meat Pasta Dish", 211, 75},
    {"Mixed Shake", 212, 60},
    {"Miracle Dinner", 213, 50},
    {"Megaton Dinner", 214, 83},
    {"Lovely Chocolate", 215, 45},
    {NULL, -1, -1}};

ItemData yoldTownShopOverrides[] = {
    {"Fire Burst", 65, 0x4},
    {"Ice Storm", 66, 0x1E},
    {"Thunder Rage", 67, 0x64},
    {"Shooting Star", 68, 0x96},
    {"POW Block", 69, 0x1E},
    {"Shroom Shake", 80, 0x6},
    {"Long-Last Shake", 85, 0x8},
    {"Life Shroom", 84, 0x19},
    {"Sleepy Sheep", 78, 0xD},
    {"Shell Shock", 70, 0x4},
    {"Mighty Tonic", 75, 0x19},
    {"Courage Shell", 74, 0xD},
    {"Volt Shroom", 76, 0xA},
    {"Gold Bar", 71, 0x78},
    {"Gold Bar x3", 72, 0x177},
    {NULL, -1, -1}};

/* Data generated by SPM-CRACKPIPE-1337 by Yme */
/* Optimized manually also by Yme */

// Goomba, Flip Goomba, Dark Goomba, Gloomba, Headbonk Goomba, and Dark Headbonk Goomba
DropItem goombaDropItems[] = {
    {83, 100},  // Dried Shroom
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {80, 200},  // Shroom Shake
    {87, 50},   // Catch Card
};

// Spiked Goomba, Dark Spiked Goomba
DropItem spikedGoombaDropItems[] = {
    {117, 100}, // Power Steak
    {108, 100}, // Fresh Pasta Bunch
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {80, 200},  // Shroom Shake
    {87, 50},   // Catch Card
};

// Paragoomba, Dark Paragoomba
DropItem paragoombaDropItems[] = {
    {100, 100}, // Peachy Peach
    {101, 100}, // Keel Mango
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {80, 200},  // Shroom Shake
    {87, 50},   // Catch Card
};

// All base Koopa Troopa variants, all Paratroopa variants
DropItem koopaTroopaDropItems[] = {
    {104, 100}, // Turtley Leaf
    {87, 10},   // Catch Card
};

// Koopatrol
DropItem koopatrolDropItems[] = {
    {104, 100}, // Turtley Leaf
    {67, 300},  // Thunder Rage
    {87, 20},   // Catch Card
};

// Buzzy Beetles/Parabuzzies & all Cleft variants
DropItem buzzyAndCleftDropItems[] = {
    {83, 100},  // Dried Shroom
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {74, 800},  // Courage Shell
    {87, 50},   // Catch Card
};

// Spike Tops/Spiky Parabuzzy
DropItem spikeTopDropItems[] = {
    {117, 100}, // Power Steak
    {105, 100}, // Cake Mix
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {74, 800},  // Courage Shell
    {87, 50},   // Catch Card
};

// Stone Buzzy
DropItem stoneBuzzyDropItems[] = {
    {100, 100}, // Peachy Peach
    {105, 100}, // Cake Mix
    {109, 100}, // Hot Sauce
    {107, 100}, // Horsetail
    {74, 800},  // Courage Shell
    {87, 50},   // Catch Card
};

// Lakitu
DropItem lakituDropItems[] = {
    {67, 100}, // Thunder Rage
    {86, 100}, // Mystery Box
    {80, 100}, // Shroom Shake
    {87, 30},  // Catch Card
};

// Spiny
DropItem spinyDropItems[] = {
    {117, 100}, // Power Steak
    {108, 100}, // Fresh Pasta Bunch
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {75, 800},  // Mighty Tonic
    {87, 50},   // Catch Card
};

// All Bones variants
DropItem bonesDropItems[] = {
    {83, 100},  // Dried Shroom
    {80, 100},  // Shroom Shake
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {66, 800},  // Ice Storm
    {87, 50},   // Catch Card
};

// Hammer Bros and Boomerang Bros
DropItem hbBrosDropItems[] = {
    {81, 100},  // Super Shroom Shake
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {65, 400},  // Fire Burst
    {87, 50},   // Catch Card
};

// Fire Bros
DropItem fBrosDropItems[] = {
    {81, 100},  // Super Shroom Shake
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {65, 800},  // Fire Burst
    {87, 50},   // Catch Card
};

// All Magikoopa variants
DropItem magikoopaDropItems[] = {
    {104, 100}, // Turtley Leaf
    {65, 100},  // Fire Burst
    {66, 100},  // Ice Storm
    {67, 100},  // Thunder Rage
    {87, 100},  // Catch Card
};

// Koopa Striker
DropItem koopaStrikerDropItems[] = {
    {80, 100},  // Shroom Shake
    {104, 100}, // Turtley Leaf
    {87, 20},   // Catch Card
};

// All other Strikers
DropItem strikerDropItems[] = {
    {81, 100},  // Super Shroom Shake
    {104, 200}, // Turtley Leaf
    {87, 20},   // Catch Card
};

// Piranha Plant
DropItem piranhaPlantDropItems[] = {
    {100, 100}, // Peachy Peach
    {101, 100}, // Keel Mango
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {87, 40},   // Catch Card
};

// Putrid Piranha
DropItem putridPiranhaDropItems[] = {
    {100, 100}, // Peachy Peach
    {101, 200}, // Keel Mango
    {114, 100}, // Fresh Veggie
    {107, 600}, // Horsetail
    {87, 40},   // Catch Card
};

// Frost Piranha
DropItem frostPiranhaDropItems[] = {
    {66, 100}, // Ice Storm
    {87, 10},  // Catch Card
};

// Boo
DropItem booDropItems[] = {
    {100, 100}, // Peachy Peach
    {101, 100}, // Keel Mango
    {85, 100},  // Long-Last Shake
    {107, 100}, // Horsetail
    {78, 400},  // Sleepy Sheep
    {77, 400},  // Ghost Shroom
    {87, 50},   // Catch Card
};

// Dark Boo and Dark Dark Boo
DropItem darkBooDropItems[] = {
    {100, 100}, // Peachy Peach
    {101, 100}, // Keel Mango
    {85, 100},  // Long-Last Shake
    {107, 100}, // Horsetail
    {78, 400},  // Sleepy Sheep
    {77, 800},  // Ghost Shroom
    {87, 50},   // Catch Card
};

// Atomic Boo
DropItem atomicBooDropItems[] = {
    {77, 100}, // Ghost Shroom
    {87, 10},  // Catch Card
};

// Cheep Cheeps and Bittacuda
DropItem cheepsAndBittacudaDropItems[] = {
    {117, 100}, // Power Steak
    {80, 100},  // Shroom Shake
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {76, 800},  // Volt Shroom
    {87, 50},   // Catch Card
};

// Bloopers
DropItem blooperDropItems[] = {
    {110, 100}, // Inky Sauce
    {87, 10},   // Catch Card
};

// Clubbas
DropItem clubbaDropItems[] = {
    {117, 100}, // Power Steak
    {108, 100}, // Fresh Pasta Bunch
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {65, 800},  // Fire Burst
    {87, 50},   // Catch Card
};

// Fuzzy
DropItem baseFuzzyDropItems[] = {
    {83, 100},  // Dried Shroom
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {84, 400},  // Life Shroom
    {87, 50},   // Catch Card
};

// Pink Fuzzy and Dark Fuzzy
DropItem fuzzyDropItems[] = {
    {83, 100},  // Dried Shroom
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {84, 400},  // Life Shroom
    {87, 10},   // Catch Card
};

// Pokey
DropItem basePokeyDropItems[] = {
    {100, 100}, // Peachy Peach
    {80, 100},  // Shroom Shake
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {87, 40},   // Catch Card
};

// Poison Pokey and Dark Pokey
DropItem pokeyDropItems[] = {
    {100, 100}, // Peachy Peach
    {80, 100},  // Shroom Shake
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {83, 800},  // Dried Shroom
    {87, 50},   // Catch Card
};

// Swooper
DropItem swooperDropItems[] = {
    {100, 100}, // Peachy Peach
    {80, 100},  // Shroom Shake
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {78, 800},  // Sleepy Sheep
    {87, 50},   // Catch Card
};

// Ruff Puffs
DropItem ruffPuffDropItems[] = {
    {80, 100},  // Shroom Shake
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {85, 800},  // Long-Last Shake
    {87, 50},   // Catch Card
};

// Spania
DropItem spaniaDropItems[] = {
    {85, 100},  // Long-Last Shake
    {101, 100}, // Keel Mango
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {86, 800},  // Mystery Box
    {87, 50},   // Catch Card
};

// Crazee Dayzee
DropItem crazeeDayzeeDropItems[] = {
    {111, 100}, // Dayzee Tear
    {87, 10},   // Catch Card
};

// Amazy Dayzee, Dark Dayzee
DropItem dayzeeDropItems[] = {
    {103, 200}, // Golden Leaf
    {111, 100}, // Dayzee Tear
    {87, 20},   // Catch Card
};

// Lava Bubble
DropItem lavaBubbleDropItems[] = {
    {65, 100}, // Fire Burst
    {87, 10},  // Catch Card
};

// Chain Chomp, Dark Chomp
DropItem chainChompDropItems[] = {
    {117, 100}, // Power Steak
    {67, 200},  // Thunder Rage
    {80, 100},  // Shroom Shake
    {87, 30},   // Catch Card
};

// Red Chomp
DropItem redChompDropItems[] = {
    {117, 100}, // Power Steak
    {69, 200},  // POW Block
    {80, 100},  // Shroom Shake
    {87, 30},   // Catch Card
};

// Squiglet
DropItem squigletDropItems[] = {
    {100, 100}, // Peachy Peach
    {80, 100},  // Shroom Shake
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {65, 400},  // Fire Burst
    {87, 50},   // Catch Card
};

// Squig
DropItem squigDropItems[] = {
    {117, 100}, // Power Steak
    {80, 100},  // Shroom Shake
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {66, 400},  // Ice Storm
    {87, 50},   // Catch Card
};

// Squog, Dark Squiglet
DropItem squogDropItems[] = {
    {117, 100}, // Power Steak
    {80, 100},  // Shroom Shake
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {67, 400},  // Thunder Rage
    {87, 50},   // Catch Card
};

// Squoinker
DropItem squoinkerDropItems[] = {
    {83, 100},  // Dried Shroom
    {80, 100},  // Shroom Shake
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {68, 400},  // Shooting Star
    {87, 50},   // Catch Card
};

// Sproing-Oing and all Choppa variants
DropItem sproingAndChoppaDropItems[] = {
    {83, 100},  // Dried Shroom
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {85, 400},  // Long-Last Shake
    {87, 50},   // Catch Card
};

// All Mini-Sproing variants
DropItem miniOingDropItems[] = {
    {83, 100}, // Dried Shroom
    {87, 10},  // Catch Card
};

// All other large Oing variants
DropItem oingDropItems[] = {
    {100, 100}, // Peachy Peach
    {101, 100}, // Keel Mango
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {85, 400},  // Long-Last Shake
    {87, 50},   // Catch Card
};

// All Boomboxer variants
DropItem boomboxerDropItems[] = {
    {100, 100}, // Peachy Peach
    {101, 100}, // Keel Mango
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {76, 400},  // Volt Shroom
    {87, 50},   // Catch Card
};

// Mister I
DropItem mrIDropItems[] = {
    {83, 100},  // Dried Shroom
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {80, 100},  // Shroom Shake
    {78, 800},  // Sleepy Sheep
    {87, 50},   // Catch Card
};

// Shlurp
DropItem shlurpDropItems[] = {
    {117, 100}, // Power Steak
    {108, 100}, // Fresh Pasta Bunch
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {65, 400},  // Fire Burst
    {69, 400},  // POW Block
    {87, 50},   // Catch Card
};

// Shlorp, Dark Shlurp
DropItem shlorpDropItems[] = {
    {117, 100}, // Power Steak
    {108, 100}, // Fresh Pasta Bunch
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {65, 400},  // Fire Burst
    {69, 800},  // POW Block
    {87, 50},   // Catch Card
};

// Tileoids G and B
DropItem tileoidGBDropItems[] = {
    {100, 100}, // Peachy Peach
    {101, 100}, // Keel Mango
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {73, 400},  // Block Block
    {79, 800},  // Stop Watch
    {87, 50},   // Catch Card
};

// Tileoid R
DropItem tileoidRDropItems[] = {
    {117, 100}, // Power Steak
    {108, 100}, // Fresh Pasta Bunch
    {109, 100}, // Hot Sauce
    {115, 100}, // Smelly Herb
    {73, 400},  // Block Block
    {79, 400},  // Stop Watch
    {87, 50},   // Catch Card
};

// Tileoid Y and Dark Tileoid
DropItem tileoidYDDropItems[] = {
    {83, 100},  // Dried Shroom
    {108, 100}, // Fresh Pasta Bunch
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {73, 400},  // Block Block
    {79, 400},  // Stop Watch
    {87, 50},   // Catch Card
};

// Jawbus
DropItem jawbusDropItems[] = {
    {65, 300}, // Fire Burst
    {66, 200}, // Ice Storm
    {67, 100}, // Thunder Rage
    {87, 30},  // Catch Card
};

// Rawbus
DropItem rawbusDropItems[] = {
    {65, 100}, // Fire Burst
    {66, 100}, // Ice Storm
    {67, 100}, // Thunder Rage
    {87, 30},  // Catch Card
};

// Gawbus, Dark Jawbus
DropItem gawbusDropItems[] = {
    {65, 100}, // Fire Burst
    {66, 200}, // Ice Storm
    {67, 300}, // Thunder Rage
    {87, 30},  // Catch Card
};

// Jellien
DropItem jellienDropItems[] = {
    {83, 100},  // Dried Shroom
    {105, 100}, // Cake Mix
    {118, 100}, // Big Egg
    {116, 100}, // Honey Jar
    {76, 400},  // Volt Shroom
    {67, 200},  // Thunder Rage
    {87, 50},   // Catch Card
};

// Foton and Warpid
DropItem fotonWarpidDropItems[] = {
    {100, 100}, // Peachy Peach
    {68, 50},   // Shooting Star
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {79, 800},  // Stop Watch
    {87, 50},   // Catch Card
};

// All Eeligon/Hooligon variants
DropItem eeligonDropItems[] = {
    {117, 100}, // Power Steak
    {108, 100}, // Fresh Pasta Bunch
    {109, 100}, // Hot Sauce
    {85, 100},  // Long-Last Shake
    {73, 800},  // Block Block
    {87, 50},   // Catch Card
};

// All Longator variants
DropItem longatorDropItems[] = {
    {100, 100}, // Peachy Peach
    {80, 100},  // Shroom Shake
    {114, 100}, // Fresh Veggie
    {107, 100}, // Horsetail
    {79, 800},  // Stop Watch
    {87, 50},   // Catch Card
};

// All Barribad variants
DropItem barribadDropItems[] = {
    {117, 100}, // Power Steak
    {80, 100},  // Shroom Shake
    {109, 100}, // Hot Sauce
    {73, 1200}, // Block Block
    {87, 50},   // Catch Card
};

// Pigarithm
DropItem pigarithmDropItems[] = {
    {85, 200}, // Long-Last Shake
    {67, 200}, // Thunder Rage
    {70, 200}, // Shell Shock
    {76, 200}, // Volt Shroom
    {78, 200}, // Sleepy Sheep
    {86, 200}, // Mystery Box
    {87, 50},  // Catch Card
};

// Hogarithm and Dark Pigarithm
DropItem hogarithmDropItems[] = {
    {85, 200}, // Long-Last Shake
    {68, 200}, // Shooting Star
    {73, 200}, // Block Block
    {77, 200}, // Ghost Shroom
    {79, 200}, // Stop Watch
    {75, 200}, // Mighty Tonic
    {87, 50},  // Catch Card
};

// Floro Cragniens
DropItem floroCragnienDropItems[] = {
    {101, 100}, // Keel Mango
    {102, 100}, // Primordial Fruit
    {87, 20},   // Catch Card
};

// Floro Sapiens
DropItem floroSapienDropItems[] = {
    {112, 100}, // Sap Soup
    {87, 10},   // Catch Card
};

// Ninjoe
DropItem ninjoeDropItems[] = {
    {67, 100}, // Thunder Rage
    {76, 100}, // Volt Shroom
    {79, 200}, // Stop Watch
    {80, 100}, // Shroom Shake
    {87, 30},  // Catch Card
};

// Ninjohn
DropItem ninjohnDropItems[] = {
    {67, 100}, // Thunder Rage
    {76, 200}, // Volt Shroom
    {79, 100}, // Stop Watch
    {80, 100}, // Shroom Shake
    {87, 30},  // Catch Card
};

// Ninjerry, Dark Ninjoe
DropItem ninjerryDropItems[] = {
    {67, 200}, // Thunder Rage
    {76, 100}, // Volt Shroom
    {79, 100}, // Stop Watch
    {81, 100}, // Super Shroom Shake
    {87, 30},  // Catch Card
};

// All unspiked Skellobits, all Skellobombers, all Skellobaits
DropItem skellobitDropItems[] = {
    {118, 100}, // Big Egg
    {117, 100}, // Power Steak
    {100, 100}, // Peachy Peach
    {66, 300},  // Ice Storm
    {77, 100},  // Ghost Shroom
    {80, 100},  // Shroom Shake
    {87, 50},   // Catch Card
};

// All spiked Skellobits
DropItem spikySkellobitDropItems[] = {
    {118, 100}, // Big Egg
    {117, 100}, // Power Steak
    {100, 100}, // Peachy Peach
    {69, 300},  // POW Block
    {77, 100},  // Ghost Shroom
    {81, 100},  // Super Shroom Shake
    {87, 50},   // Catch Card
};

// Blue Magiblot
DropItem magiblotBDropItems[] = {
    {87, 200}, // Catch Card
    {88, 100}, // Catch Card SP
    {80, 100}, // Shroom Shake
};

// Red Magiblot
DropItem magiblotRDropItems[] = {
    {87, 300}, // Catch Card
    {88, 100}, // Catch Card SP
    {80, 100}, // Shroom Shake
};

// Yellow Magiblot, Dark Magiblot
DropItem magiblotYDDropItems[] = {
    {87, 100}, // Catch Card
    {88, 100}, // Catch Card SP
    {80, 100}, // Shroom Shake
};

// All Cursyas
DropItem cursyaDropItems[] = {
    {98, 100}, // Poison Shroom
    {87, 10},  // Catch Card
};

// Megabite
DropItem megabiteDropItems[] = {
    {68, 100}, // Shooting Star
    {77, 200}, // Ghost Shroom
    {88, 200}, // Catch Card SP
    {87, 30},  // Catch Card
};

// Gigabite and Dark Megabite
DropItem gigabiteDropItems[] = {
    {69, 100}, // POW Block
    {77, 100}, // Ghost Shroom
    {88, 100}, // Catch Card SP
    {87, 30},  // Catch Card
};

// All Muth variants
DropItem muthDropItems[] = {
    {113, 100}, // Bone-In Cut
    {87, 10},   // Catch Card
};

// Cherbil, Dark Cherbil
DropItem cherbilDropItems[] = {
    {100, 100}, // Peachy Peach
    {78, 100},  // Sleepy Sheep
    {85, 100},  // Long-Last Shake
    {87, 20},   // Catch Card
};

// Poison Cherbil
DropItem cherbilPDropItems[] = {
    {100, 100}, // Peachy Peach
    {83, 500},  // Dried Shroom
    {85, 50},   // Long-Last Shake
    {87, 20},   // Catch Card
};

// Ice Cherbil
DropItem cherbilIDropItems[] = {
    {100, 100}, // Peachy Peach
    {66, 100},  // Ice Storm
    {85, 100},  // Long-Last Shake
    {87, 20},   // Catch Card
};

NPCData npcData[] = {
    {"Goomba", 0, 4, goombaDropItems, 6},
    {"Flip Goomba", 1, 3, goombaDropItems, 6},
    {"Dark Goomba", 2, 4, goombaDropItems, 6},
    {"Gloomba", 3, 3, goombaDropItems, 6},
    {"Spiked Goomba", 4, 3, spikedGoombaDropItems, 6},
    {"Dark Spiked Goomba", 6, 4, spikedGoombaDropItems, 6},
    {"Paragoomba", 7, 3, paragoombaDropItems, 6},
    {"Dark Paragoomba", 8, 4, paragoombaDropItems, 6},
    {"Headbonk Goomba", 9, 3, goombaDropItems, 6},
    {"Dark Headbonk Goomba", 10, 4, goombaDropItems, 6},
    {"Koopa Troopa", 11, 9, koopaTroopaDropItems, 2},
    {"Koopa Troopa", 12, 9, koopaTroopaDropItems, 2}, // No sunglasses
    {"Koopa Troopa", 13, 9, koopaTroopaDropItems, 2}, // IDK
    {"Red Koopa Troopa", 14, 9, koopaTroopaDropItems, 2},
    {"Flip Koopa Troopa", 15, 9, koopaTroopaDropItems, 2},
    {"Dark Koopa", 16, 5, koopaTroopaDropItems, 2},
    {"Koopatrol", 18, 5, koopatrolDropItems, 3},
    {"Dark Koopatrol", 19, 7, koopatrolDropItems, 3},
    {"Paratroopa", 20, 3, koopaTroopaDropItems, 2},
    {"Paratroopa", 21, 3, koopaTroopaDropItems, 2},
    {"Paratroopa", 22, 3, koopaTroopaDropItems, 2},
    {"Paratroopa", 23, 3, koopaTroopaDropItems, 2},
    {"Dark Paratroopa", 24, 5, koopaTroopaDropItems, 2},
    {"Buzzy Beetle", 25, 3, buzzyAndCleftDropItems, 6},
    {"Buzzy Beetle", 26, 3, buzzyAndCleftDropItems, 6}, // Upside-down
    {"Spike Top", 27, 3, spikeTopDropItems, 6},
    {"Spike Top", 28, 3, spikeTopDropItems, 6}, // Upside-down
    {"Dark Spike Top", 29, 5, spikeTopDropItems, 6},
    {"Parabuzzy", 30, 3, buzzyAndCleftDropItems, 6},
    {"Spiky Parabuzzy", 31, 3, spikeTopDropItems, 6},
    {"Stone Buzzy", 32, 3, stoneBuzzyDropItems, 6},
    {"Dark Stone Buzzy", 33, 5, stoneBuzzyDropItems, 6},
    {"Lakitu", 34, 10, lakituDropItems, 4},
    {"Flip Lakitu", 35, 10, lakituDropItems, 4},
    {"Spiny", 36, 3, spinyDropItems, 6},
    {"Flip Spiny", 37, 3, spinyDropItems, 6},
    {"Dark Spiny", 38, 5, spinyDropItems, 6},
    {"Dry Bones", 39, 3, bonesDropItems, 6},
    {"Dull Bones", 41, 4, bonesDropItems, 6},
    {"Dark Dull Bones", 43, 4, bonesDropItems, 6},
    {"Hammer Bro", 45, 5, hbBrosDropItems, 6},
    {"Flip Hammer Bro", 47, 5, hbBrosDropItems, 6},
    {"Dark Hammer Bro", 49, 7, hbBrosDropItems, 6},
    {"Boomerang Bro", 51, 5, hbBrosDropItems, 6},
    {"Flip Boomerang Bro", 53, 5, hbBrosDropItems, 6},
    {"Dark Boomerang Bro", 55, 7, hbBrosDropItems, 6},
    {"Fire Bro", 57, 5, fBrosDropItems, 6},
    {"Flip Fire Bro", 59, 5, fBrosDropItems, 6},
    {"Dark Fire Bro", 61, 7, fBrosDropItems, 6},
    {"Magikoopa", 63, 5, magikoopaDropItems, 5},
    {"Broom Magikoopa", 64, 5, magikoopaDropItems, 5},
    {"Dark Magikoopa", 66, 7, magikoopaDropItems, 5},
    {"Dark Broom Magikoopa", 67, 7, magikoopaDropItems, 5},
    {"Koopa Striker", 69, 5, koopaStrikerDropItems, 3},
    {"Toopa Striker", 71, 5, strikerDropItems, 3},
    {"Soopa Striker", 73, 5, strikerDropItems, 3},
    {"Dark Striker", 75, 7, strikerDropItems, 3},
    {"Piranha Plant", 77, 10, piranhaPlantDropItems, 5},
    {"Putrid Piranha", 78, 100, putridPiranhaDropItems, 5},
    {"Frost Piranha", 80, 10, frostPiranhaDropItems, 2},
    {"Bill Blaster", 83, 0, NULL, 0},
    {"Boo", 84, 4, booDropItems, 7},
    {"Dark Boo", 85, 4, darkBooDropItems, 7},
    {"Dark Dark Boo", 86, 6, darkBooDropItems, 7},
    {"Atomic Boo", 87, 20, atomicBooDropItems, 2},
    {"Cheep Cheep", 88, 3, cheepsAndBittacudaDropItems, 6},
    {"Red Cheep Cheep", 89, 3, cheepsAndBittacudaDropItems, 6},
    {"Flip Cheep Cheep", 90, 3, cheepsAndBittacudaDropItems, 6},
    {"Blooper", 91, 15, blooperDropItems, 2},
    {"Flip Blooper", 92, 15, blooperDropItems, 2},
    {"Bittacuda", 93, 7, cheepsAndBittacudaDropItems, 6},
    {"Clubba", 94, 3, clubbaDropItems, 6},
    {"Dark Clubba", 95, 5, clubbaDropItems, 6},
    {"Fuzzy", 96, 3, baseFuzzyDropItems, 6},
    {"Pink Fuzzy", 97, 3, fuzzyDropItems, 6},
    {"Dark Fuzzy", 98, 5, fuzzyDropItems, 6},
    {"Bald Cleft", 99, 4, buzzyAndCleftDropItems, 6},
    {"Moon Cleft", 100, 4, buzzyAndCleftDropItems, 6},
    {"Dark Cleft", 101, 5, buzzyAndCleftDropItems, 6},
    {"Pokey", 102, 3, basePokeyDropItems, 5},
    {"Poison Pokey", 104, 100, pokeyDropItems, 6},
    {"Dark Pokey", 106, 50, pokeyDropItems, 6},
    {"Swooper", 108, 3, swooperDropItems, 6},
    {"Ruff Puff", 109, 3, ruffPuffDropItems, 6},
    {"Dark Ruff Puff", 111, 4, ruffPuffDropItems, 6},
    {"Spania", 113, 3, spaniaDropItems, 6},
    {"Dark Spania", 114, 5, NULL, 0},
    {"Crazee Dayzee", 115, 15, crazeeDayzeeDropItems, 2},
    {"Amazy Dayzee", 117, 70, dayzeeDropItems, 3},
    {"Dark Dayzee", 119, 15, dayzeeDropItems, 3},
    {"Lava Bubble", 121, 4, lavaBubbleDropItems, 2},
    {"Chain Chomp", 122, 5, chainChompDropItems, 4},
    {"Red Chomp", 123, 5, redChompDropItems, 4},
    {"Dark Chomp", 124, 7, chainChompDropItems, 4},
    {"Squiglet", 125, 3, squigletDropItems, 6},
    {"Squig", 126, 3, squigDropItems, 6},
    {"Squog", 128, 3, squogDropItems, 6},
    {"Squoinker", 130, 3, squoinkerDropItems, 6},
    {"Dark Squiglet", 132, 5, squogDropItems, 6},
    {"Sproing-Oing", 134, 5, sproingAndChoppaDropItems, 6},
    {"Mini-Sproing", 135, 2, miniOingDropItems, 2},
    {"Boing-Oing", 136, 5, oingDropItems, 6},
    {"Mini-Boing", 137, 2, miniOingDropItems, 2},
    {"Zoing-Oing", 138, 5, oingDropItems, 6},
    {"Mini-Zoing", 139, 2, miniOingDropItems, 2},
    {"Dark Sproing-Oing", 140, 7, oingDropItems, 6},
    {"Dark Mini-Sproing", 141, 3, miniOingDropItems, 2},
    {"Boomboxer", 142, 3, boomboxerDropItems, 6},
    {"Beepboxer", 144, 3, boomboxerDropItems, 6},
    {"Blastboxer", 146, 3, boomboxerDropItems, 6},
    {"Dark Boomboxer", 148, 5, boomboxerDropItems, 6},
    {"Mister I", 150, 10, mrIDropItems, 6},
    {"Red I", 152, 10, mrIDropItems, 6},
    {"Shlurp", 156, 3, shlurpDropItems, 7},
    {"Shlorp", 157, 3, shlorpDropItems, 7},
    {"Dark Shlurp", 158, 4, shlorpDropItems, 7},
    {"Growmeba", 159, 0, NULL, 0},
    {"Blomeba", 160, 0, NULL, 0},
    {"Chromeba", 161, 0, NULL, 0},
    {"Dark Growmeba", 162, 0, NULL, 0},
    {"Tileoid G", 163, 3, tileoidGBDropItems, 7},
    {"Tileoid B", 164, 3, tileoidGBDropItems, 7},
    {"Tileoid R", 165, 3, tileoidRDropItems, 7},
    {"Tileoid Y", 166, 3, tileoidYDDropItems, 7},
    {"Dark Tileoid", 167, 5, tileoidYDDropItems, 7},
    {"Jawbus", 168, 10, jawbusDropItems, 4},
    {"Rawbus", 169, 10, rawbusDropItems, 4},
    {"Gawbus", 170, 10, gawbusDropItems, 4},
    {"Dark Jawbus", 171, 15, gawbusDropItems, 4},
    {"BigMeow", 172, 0, NULL, 0},
    {"PatrolMeow", 173, 0, NULL, 0},
    {"AirMeow", 174, 0, NULL, 0},
    {"SurpriseMeow", 175, 0, NULL, 0},
    {"Jellien", 178, 2, jellienDropItems, 7},
    {"Foton", 179, 2, fotonWarpidDropItems, 6},
    {"Warpid", 181, 2, fotonWarpidDropItems, 6},
    {"Eeligon", 182, 5, eeligonDropItems, 6},
    {"Hooligon", 184, 5, eeligonDropItems, 6},
    {"Dark Eeligon", 186, 7, eeligonDropItems, 6},
    {"Longator", 188, 3, longatorDropItems, 6},
    {"Longadile", 189, 3, longatorDropItems, 6},
    {"Dark Longator", 190, 5, longatorDropItems, 6},
    {"Choppa", 191, 3, sproingAndChoppaDropItems, 6},
    {"Copta", 192, 3, sproingAndChoppaDropItems, 6},
    {"Dark Choppa", 193, 5, sproingAndChoppaDropItems, 6},
    {"Barribad", 194, 5, barribadDropItems, 5},
    {"Sobarribad", 196, 5, barribadDropItems, 5},
    {"Dark Barribad", 198, 7, barribadDropItems, 5},
    {"Pigarithm", 200, 5, pigarithmDropItems, 7},
    {"Hogarithm", 201, 5, hogarithmDropItems, 7},
    {"Dark Pigarithm", 202, 7, hogarithmDropItems, 7},
    {"Floro Cragnien", 203, 7, floroCragnienDropItems, 3},
    {"Floro Cragnien", 204, 7, floroCragnienDropItems, 3},
    {"Floro Sapien", 205, 8, floroSapienDropItems, 2},
    {"Floro Sapien", 207, 8, floroSapienDropItems, 2},
    {"Floro Sapien", 209, 8, floroSapienDropItems, 2},
    {"Ninjoe", 211, 7, ninjoeDropItems, 5},
    {"Ninjohn", 214, 8, ninjohnDropItems, 5},
    {"Ninjerry", 217, 9, ninjerryDropItems, 5},
    {"Dark Ninjoe", 220, 10, ninjerryDropItems, 5},
    {"Skellobit", 223, 3, skellobitDropItems, 7},
    {"Flip Skellobit", 224, 3, skellobitDropItems, 7},
    {"Dark Skellobit", 225, 5, skellobitDropItems, 7},
    {"Spiky Skellobit", 226, 5, spikySkellobitDropItems, 7},
    {"Flip Spiky Skellobit", 227, 5, spikySkellobitDropItems, 7},
    {"Dark Spiky Skellobit", 228, 7, spikySkellobitDropItems, 7},
    {"Skellobomber", 229, 3, skellobitDropItems, 7},      // Throws head at you
    {"Flip Skellobomber", 230, 3, skellobitDropItems, 7}, // ^
    {"Skellobomber", 232, 3, skellobitDropItems, 7},      // Holds skellobait
    {"Flip Skellobomber", 233, 3, skellobitDropItems, 7}, // ^
    {"Skellobait", 234, 2, skellobitDropItems, 7},
    {"Spiky Skellobait", 235, 2, skellobitDropItems, 7},
    {"Blue Magiblot", 237, 4, magiblotBDropItems, 3},
    {"Red Magiblot", 239, 4, magiblotRDropItems, 3},
    {"Yellow Magiblot", 241, 4, magiblotYDDropItems, 3},
    {"Dark Magiblot", 243, 6, magiblotYDDropItems, 3},
    {"Cursya", 245, 10, cursyaDropItems, 2},
    {"Back Cursya", 246, 10, cursyaDropItems, 2},
    {"Tech Cursya", 247, 10, cursyaDropItems, 2},
    {"Heavy Cursya", 248, 10, cursyaDropItems, 2},
    {"Reversya Cursya", 249, 10, cursyaDropItems, 2},
    {"Dark Cursya", 250, 15, cursyaDropItems, 2},
    {"Dark Tech Cursya", 251, 15, cursyaDropItems, 2},
    {"Dark Heavy Cursya", 252, 15, cursyaDropItems, 2},
    {"Dark Reversya Cursya", 253, 15, cursyaDropItems, 2},
    {"Megabite", 254, 10, megabiteDropItems, 4},
    {"Gigabite", 255, 10, gigabiteDropItems, 4},
    {"Dark Megabite", 256, 15, gigabiteDropItems, 4},
    {"Muth", 257, 20, muthDropItems, 2},
    {"Mega Muth", 258, 20, muthDropItems, 2},
    {"Dark Muth", 259, 25, muthDropItems, 2},
    {"Spiny Tromp", 266, 0, NULL, 0},
    {"Spiky Tromp", 267, 0, NULL, 0},
    {"Cherbil", 440, 4, cherbilDropItems, 4},
    {"Poison Cherbil", 442, 100, cherbilPDropItems, 4},
    {"Ice Cherbil", 444, 4, cherbilIDropItems, 4},
    {"Dark Cherbil", 446, 50, cherbilDropItems, 4},
    {NULL, 0, 0, NULL, 0}};